"""Initial migration

Revision ID: cea6831e60bf
Revises: 
Create Date: 2024-09-29 23:06:10.294731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea6831e60bf'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('children_id', sa.Integer(), nullable=False),
    sa.Column('children_name', sa.String(length=100), nullable=False),
    sa.Column('children_birth_date', sa.Date(), nullable=False),
    sa.Column('children_address', sa.String(length=255), nullable=False),
    sa.Column('children_parent', sa.String(length=100), nullable=False),
    sa.Column('children_parent_phone', sa.String(length=20), nullable=False),
    sa.Column('children_allergy', sa.String(length=255), nullable=True),
    sa.Column('children_blood_type', sa.String(length=5), nullable=True),
    sa.Column('children_weight', sa.Float(), nullable=True),
    sa.Column('children_height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('children_id', name=op.f('pk_children'))
    )
    op.create_table('health_workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_health_workers'))
    )
    op.create_table('health_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('children_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_immunization', sa.String(length=100), nullable=True),
    sa.Column('record_vaccinated_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.children_id'], name=op.f('fk_health_records_children_id_children')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_health_records'))
    )
    op.create_table('measurements',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('children_id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('measurement_weight', sa.Float(), nullable=False),
    sa.Column('measurement_height', sa.Float(), nullable=False),
    sa.Column('measurement_head_circumference', sa.Float(), nullable=True),
    sa.Column('measurement_abdominal_circumference', sa.Float(), nullable=True),
    sa.Column('measurement_leg_circumference', sa.Float(), nullable=True),
    sa.Column('measurement_arm_circumference', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.children_id'], name=op.f('fk_measurements_children_id_children')),
    sa.PrimaryKeyConstraint('measurement_id', name=op.f('pk_measurements'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('health_records')
    op.drop_table('health_workers')
    op.drop_table('children')
    # ### end Alembic commands ###
